In [11]:
import numpy as np
import random

def generate_correlation_matrix(dimensions, stronger_top_left=True):
    # Generate a random matrix
    matrix = np.zeros((dimensions, dimensions))
    
    # Introduce more 1's in the top-left corner for class 1 matrices
    for row in range(dimensions):
        for column in range(dimensions):
            if row <= column and random.random() < 0.25:
                matrix[row, column] = 1
    for i in range(dimensions//2):
        for j in range(dimensions//2):
            if i <= j:
                if stronger_top_left and random.random() < 0.75:  # 75% chance of setting a value to 1
                    matrix[i, j] = 1

    # Make the matrix symmetric
    corr_matrix = np.maximum(matrix, matrix.T)
    
    # Make the diagonal elements equal to 1
    np.fill_diagonal(corr_matrix, 1)
    
    return corr_matrix

def generate_dataset(num_samples, dimensions, stronger_top_left=True, class_ratio=0.5):
    num_class1 = int(num_samples * class_ratio)
    num_class0 = num_samples - num_class1
    
    class1_matrices = [generate_correlation_matrix(dimensions, stronger_top_left) for _ in range(num_class1)]
    class0_matrices = [generate_correlation_matrix(dimensions, stronger_top_left=False) for _ in range(num_class0)]
    
    labels = [1] * num_class1 + [0] * num_class0
    
    # Shuffle the data
    combined = list(zip(class1_matrices + class0_matrices, labels))
    random.shuffle(combined)
    corr_matrices, labels = zip(*combined)
    
    return corr_matrices, labels

# Example usage:
num_samples = 1000
dimensions = 116
class_ratio = 0.5  # Ratio of samples for class 1
matrices, labels = generate_dataset(num_samples, dimensions, stronger_top_left=True, class_ratio=class_ratio)

# matrices contain the generated correlation matrices
# labels contain the corresponding class labels

for i in range(5):
    print(matrices[i])
    print(labels[i])
    print()

[[1. 0. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 1.]
 [0. 0. 0. ... 0. 1. 1.]]
1

[[1. 0. 0. ... 0. 1. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 1.]
 [1. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 1. 0. 1.]]
0

[[1. 1. 0. ... 0. 1. 0.]
 [1. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [1. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
0

[[1. 0. 0. ... 1. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 1. 0.]
 ...
 [1. 0. 0. ... 1. 0. 1.]
 [0. 0. 1. ... 0. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]]
0

[[1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 1. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 1. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
1

